/**
 * Purpose: API route handler for creating and fetching orders
 * Author: [Author Placeholder]
 * Date: [Date Placeholder]
 */
import { NextRequest, NextResponse } from 'next/server';
import { connectDB } from '@/lib/db';
import Order from '@/models/Order';
import { OrderSchema } from '@/lib/validators';

export async function GET(request: NextRequest) {
  try {
    const adminKey = request.headers.get('x-admin-key');
    if (!adminKey || adminKey !== process.env.ADMIN_KEY) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    const { searchParams } = new URL(request.url);
    const status = searchParams.get('status');

    const query: any = {};
    if (status) {
      query.status = status;
    }

    const orders = await Order.find(query).sort({ createdAt: -1 }).lean();

    return NextResponse.json(orders);
  } catch (error) {
    console.error('Error fetching orders:', error);
    return NextResponse.json({ error: 'Failed to fetch orders' }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const data = await request.json();

    const validationResult = OrderSchema.safeParse(data);
    if (!validationResult.success) {
      return NextResponse.json(
        { error: validationResult.error.errors[0].message },
        { status: 400 },
      );
    }

    const validatedData = validationResult.data as any;

    // Calculate subtotal
    const subtotal = validatedData.items.reduce(
      (sum: number, item: any) => sum + item.priceAtPurchase * item.quantity,
      0,
    );

    const shippingFee = 200; // Flat rate as requested
    const total = subtotal + shippingFee;

    validatedData.subtotal = subtotal;
    validatedData.shippingFee = shippingFee;
    validatedData.total = total;

    await connectDB();

    // orderNumber is auto-generated by pre('save') hook in Order model
    const newOrder = new Order(validatedData);
    await newOrder.save();

    return NextResponse.json(
      {
        success: true,
        orderNumber: newOrder.orderNumber,
        total: newOrder.total,
      },
      { status: 201 },
    );
  } catch (error) {
    console.error('Error creating order:', error);
    return NextResponse.json({ error: 'Failed to create order' }, { status: 500 });
  }
}
